ballerina-platform/module-ballerina-email

.gitignore, email-ballerina/Ballerina.toml, email-ballerina/build.gradle, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java, gradle.properties
Fix a build failure due to a version mismatch
=> Match the versions of Testng dependency in build

README.md, build.gradle, email-ballerina/Ballerina.toml, email-ballerina/build.gradle, email-native/build.gradle, email-native/src/main/java/org/ballerinalang/stdlib/email/client/EmailAccessClient.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java
Fix issues related to BBE testing.
=> Fix some issues found during the migration and add a missing jar related to BBE testing

email-ballerina/src/email/imap_client_endpoint.bal, email-ballerina/src/email/listener_endpoint.bal, email-ballerina/src/email/pop_client_endpoint.bal, email-ballerina/src/email/smtp_client_endpoint.bal, email-ballerina/src/email/tests/unit-tests/ImapComplexEmailReceive.bal, email-ballerina/src/email/tests/unit-tests/ImapSimpleSecureEmailReceive.bal, email-ballerina/src/email/tests/unit-tests/ListenerImapReceive.bal, email-ballerina/src/email/tests/unit-tests/ListenerPopReceive.bal, email-ballerina/src/email/tests/unit-tests/PopComplexEmailReceive.bal, email-ballerina/src/email/tests/unit-tests/PopSimpleSecureEmailReceive.bal, email-ballerina/src/email/tests/unit-tests/SmtpComplexEmailSend.bal, email-ballerina/src/email/tests/unit-tests/SmtpSimpleSecureEmailSend.bal, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java
Update according to Ballerina API changes.
=> Update for B7A lang API changes

email-ballerina/src/email/tests/unit-tests/ListenerImapReceive.bal, email-test-utils/src/main/java/org/ballerinalang/stdlib/email/testutils/mockServerUtils/ListenerImapReceiveTest.java
Correct the IMAP port numbers in IMAP listener.
=> Correct the port numbers of IMAP mail listeners

email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListener.java
Replace Async methods with Sync methods as Sync methods are going to be deprecated.
=> Replace Sync method calls with Async calls due to API deprecation

email-native/src/main/java/org/ballerinalang/stdlib/email/client/EmailAccessClient.java, email-native/src/main/java/org/ballerinalang/stdlib/email/client/SmtpClient.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailConsumer.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListener.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListenerHelper.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/CommonUtil.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/SmtpUtil.java, email-test-utils/src/main/java/org/ballerinalang/stdlib/email/testutils/mockServerUtils/SmtpSimpleSecureEmailSendTest.java
=> Migrate jBallerina Runtime APIs

.github/workflows/pull-request.yml, email-ballerina/src/email/imap_client_endpoint.bal, email-ballerina/src/email/listener_endpoint.bal, email-ballerina/src/email/pop_client_endpoint.bal, email-ballerina/src/email/smtp_client_endpoint.bal, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListenerHelper.java
Introduce isolated keyword and do the forked repo change
=> Add changes related to introduction of isolation and forked repo change

email-ballerina/build.gradle
Add test coverage report generation.
=> Add test code coverage

build.gradle, email-native/build.gradle, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailConsumer.java
Remove Maven Snapshot repository and adding Checkstyle validation.
=> Remove Maven snapshot repo and add checkstyle

email-native/src/main/java/module-info.java, email-native/src/main/java/org/ballerinalang/stdlib/email/client/EmailAccessClient.java, email-native/src/main/java/org/ballerinalang/stdlib/email/client/SmtpClient.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailConsumer.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListener.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListenerHelper.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/CommonUtil.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/SmtpUtil.java
Refactor ballerina runtime api usages
=> Migrate ballerina runtime apis

README.md
=> Update README related to new Stdlib Repository

README.md
=> Improve issues and projects description

email-native/build.gradle, email-native/src/main/java/module-info.java, email-native/src/main/java/org/ballerinalang/stdlib/email/service/compiler/EmailListenerCompilerPlugin.java
=> Update Diagnostic API change

.github/workflows/build-master.yml, .github/workflows/pull-request.yml
$subject related to ballerina-platform/ballerina-standard-library#569
=> Update secrets related to PR build

email-ballerina/Package.md, email-ballerina/commons.bal, email-ballerina/imap_client_endpoint.bal, email-ballerina/imap_listener_endpoint.bal, email-ballerina/pop_client_endpoint.bal, email-ballerina/pop_listener_endpoint.bal, email-ballerina/smtp_client_endpoint.bal, email-ballerina/tests/ImapComplexEmailReceive.bal, email-ballerina/tests/ImapSimpleSecureEmailReceive.bal, email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal, email-ballerina/tests/PopComplexEmailReceive.bal, email-ballerina/tests/PopSimpleSecureEmailReceive.bal, email-ballerina/tests/SmtpComplexEmailSend.bal, email-ballerina/tests/SmtpSimpleSecureEmailSend.bal, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailConsumer.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListener.java, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailListenerHelper.java, email-native/src/main/java/org/ballerinalang/stdlib/email/service/compiler/EmailListenerCompilerPlugin.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java
Make new API changes to Email module.
=> Make new API changes to Email module

email-ballerina/init.bal, email-native/src/main/java/org/ballerinalang/stdlib/email/server/EmailConsumer.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailAccessUtil.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailUtils.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/ModuleUtils.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/SmtpUtil.java
> Remove hard coded ballerina version in java code
=> Remove hard coded ballerina version in java code

build.gradle, email-ballerina/Ballerina.toml, email-ballerina/build.gradle, email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal, gradle.properties
=> Migrate runtime:sleep to lang.runtime:sleep

email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal
=> Fix testerina function configs

email-ballerina/imap_listener_endpoint.bal, email-ballerina/pop_listener_endpoint.bal
=> Update Scheduler API changes

email-ballerina/build.gradle
$subject.
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Update ballerina command to bal command

email-ballerina/Package.md, email-ballerina/tests/SmtpEmailSendWithOptions.bal, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/SmtpUtil.java
=> Add missing security settings to SMTP client

build.gradle, email-ballerina/Ballerina.toml, email-ballerina/build.gradle, gradle.properties
$subject
N/A
N/A
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.
> Link to drafts of marketing …
=> Remove config module dependency

email-ballerina/imap_client_endpoint.bal, email-ballerina/init.bal, email-ballerina/pop_client_endpoint.bal, email-ballerina/pop_listener_endpoint.bal, email-ballerina/smtp_client_endpoint.bal, email-ballerina/tests/ImapComplexEmailReceive.bal, email-ballerina/tests/ImapSimpleSecureEmailReceive.bal, email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal, email-ballerina/tests/PopComplexEmailReceive.bal, email-ballerina/tests/PopSimpleSecureEmailReceive.bal, email-ballerina/tests/SmtpComplexEmailSend.bal, email-ballerina/tests/SmtpEmailSendWithOptions.bal, email-ballerina/tests/SmtpSimpleSecureEmailSend.bal
Related Issue: ballerina-platform/ballerina-lang#28034
> Describe the solutions that this feature/fix will introduce to resolve the problems described above
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.
> Summary of user stories addressed by this change>
> Brief description of the new feature or bug fix as it will appear in the release notes
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Change the name of the `java` langlib module to `jballerina.java`

email-ballerina/Ballerina.toml, email-ballerina/Dependencies.toml, email-ballerina/build.gradle
Fixes ballerina-platform/ballerina-lang#27988
=> Add Dependencies.toml

email-ballerina/build.gradle
=> Revert dependency toml file after build

.github/workflows/publish-release.yml, build.gradle, email-ballerina/build.gradle, gradle.properties
=> Enable publishing to Ballerina Central during release

build.gradle, email-ballerina/build.gradle
=> Re-order Build Tasks to Publish to the Ballerina Central

.github/workflows/pull-request.yml, gradle.properties
=> Correct the version set with an automated PR

email-ballerina/build.gradle
=> Remove publishing testable jar and exec artifacts

README.md
=> Add Codecov Badge to Github

email-ballerina/build.gradle
> Add extracted bala in the zip artifact
> Fixes ballerina-platform/ballerina-lang#27763
=> Add extracted bala in the zip artifact

email-ballerina/build.gradle
> Add -c flag to build command
> Related to ballerina-platform/ballerina-lang#29032
=> Add -c flag to build command

email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal
=> Improve code coverage and enable tests

email-ballerina/email_errors.bal, email-ballerina/pop_listener_endpoint.bal, email-ballerina/smtp_client_endpoint.bal, email-native/src/main/java/org/ballerinalang/stdlib/email/client/EmailAccessClient.java, email-native/src/main/java/org/ballerinalang/stdlib/email/client/SmtpClient.java, email-native/src/main/java/org/ballerinalang/stdlib/email/util/EmailConstants.java
$subject.
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1111
=> Move all error types to a common error type

codecov.yml
=> Remove Codecov Path Fix

email-ballerina/imap_client_endpoint.bal, email-ballerina/pop_client_endpoint.bal
Correct doc content.
Resolves https://github.com/ballerina-platform/ballerina-dev-website/issues/2040
=> Correct doc comments

build.gradle, email-ballerina/build.gradle
=> Strip stdlib dependency version

email-ballerina/build.gradle
=> Fix XML code coverage issue

changelog.md, email-ballerina/build.gradle, email-ballerina/imap_client_endpoint.bal, email-ballerina/pop_client_endpoint.bal, email-ballerina/smtp_client_endpoint.bal, email-compiler-plugin-tests/build.gradle
1. Add changelog content
2. Fix build failure due to another PR merge because of the code coverage scope
3. Fix a compiler plugin build failure scenario
4. Add missing documentation content
=> Fix build issues and doc warnings

email-ballerina/build.gradle
=> Correct code coverage missing the java content

email-ballerina/build.gradle, gradle.properties
=> Move plugin to stable version

README.md, email-ballerina/Module.md, email-ballerina/Package.md, email-ballerina/imap_listener_endpoint.bal, email-ballerina/pop_client_endpoint.bal, email-ballerina/pop_listener_endpoint.bal, email-ballerina/smtp_client_endpoint.bal
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1351
=> Update docs in email module

email-ballerina/imap_listener_endpoint.bal, email-ballerina/pop_listener_endpoint.bal, email-ballerina/tests/ListenerImapReceive.bal
=> Make start and stop operations of listeners as info logs

email-ballerina/Package.md
=> Correct the Ballerina site link

email-ballerina/Package.md
Relates to https://github.com/ballerina-platform/ballerina-standard-library/issues/1462
=> Update Package.md links into HTML format

email-ballerina/imap_listener_endpoint.bal, email-ballerina/pop_listener_endpoint.bal, email-ballerina/tests/ImapComplexEmailReceive.bal, email-ballerina/tests/ImapSimpleEmailReceive.bal, email-ballerina/tests/ImapSimpleSecureEmailReceive.bal, email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal, email-ballerina/tests/PopComplexEmailReceive.bal, email-ballerina/tests/PopSimpleEmailReceive.bal, email-ballerina/tests/PopSimpleSecureEmailReceive.bal, email-ballerina/tests/SmtpComplexEmailSend.bal, email-ballerina/tests/SmtpEmailSendWithOptions.bal, email-ballerina/tests/SmtpSimpleSecureEmailSend.bal, email-ballerina/tests/SmtpSimpleSecureEmailSendWithOptions.bal
=> Remove tainted keyword

email-ballerina/Module.md, email-ballerina/Package.md, gradle.properties
=> Make the Ballerina link to be opened in a new window

email-ballerina/Module.md
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1554
=> Change doc style to be similar with other docs

email-ballerina/email_errors.bal
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1553
=> Add a full stop in docs

email-ballerina/imap_client_endpoint.bal, email-ballerina/pop_client_endpoint.bal, email-ballerina/smtp_client_endpoint.bal
$subject
IMAP and POP3 listener configuration APIs are not changed as the changes are breaking the API.
=> Change client configs to include record parameters

changelog.md, email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal, email-native/src/main/java/org/ballerinalang/stdlib/email/client/EmailAccessClient.java
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/1574
=> Avoid POP listener continuously receiving the same email message

email-ballerina/tests/ListenerImapReceive.bal, email-ballerina/tests/ListenerPopReceive.bal, email-test-utils/src/main/java/org/ballerinalang/stdlib/email/testutils/ListenerImapReceiveTest.java, email-test-utils/src/main/java/org/ballerinalang/stdlib/email/testutils/ListenerPopReceiveTest.java
$subject
Relates to https://github.com/ballerina-platform/ballerina-standard-library/issues/1574
=> Improve to test the listened emails after the first listened email

.github/workflows/publish-release.yml, ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, ballerina/build.gradle, ballerina/imap_listener_endpoint.bal, build-config/resources/Ballerina.toml, build-config/resources/CompilerPlugin.toml, gradle.properties
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1746
=> Make the Ballerina Project Tooling Friendly

.github/workflows/central-publish.yml, .github/workflows/publish-release.yml, .github/workflows/trivy-scan.yml, ballerina/Dependencies.toml
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/1958
=> Skip build directory from Trivy scan

ballerina/imap_listener_endpoint.bal, ballerina/pop_listener_endpoint.bal
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2040
=> Remove start and stop logs of email listeners

ballerina/commons.bal, ballerina/imap_listener_endpoint.bal, ballerina/pop_listener_endpoint.bal, ballerina/tests/ListenerImapReceive.bal, ballerina/tests/ListenerPopReceive.bal, changelog.md, gradle.properties
$subject related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2398
=> Make email service-type distinct

compiler-plugin-tests/build.gradle, compiler-plugin-tests/src/test/java/io/ballerina/stdlib/email/compiler/CompilerPluginTest.java, gradle.properties
$Subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/2396
=> Update gradle plugin version

ballerina/Dependencies.toml, native/src/main/java/io/ballerina/stdlib/email/server/EmailListener.java
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/2383
=> Migrate to latest ballerina runtime APIs

build.gradle
=> Make it build during the release

native/src/main/java/io/ballerina/stdlib/email/server/EmailConnector.java, native/src/main/java/io/ballerina/stdlib/email/server/EmailConsumer.java, native/src/main/java/io/ballerina/stdlib/email/server/EmailListenerHelper.java
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2443
=> Avoid throwing exceptions from native Java methods

ballerina/tests/ImapSimpleEmailReceive.bal, ballerina/tests/ImapSimpleSecureEmailReceive.bal, ballerina/tests/ListenerImapReceive.bal, ballerina/tests/ListenerPopReceive.bal, ballerina/tests/PopComplexEmailReceive.bal, ballerina/tests/PopSimpleEmailReceive.bal, ballerina/tests/PopSimpleSecureEmailReceive.bal, ballerina/tests/SmtpComplexEmailSend.bal, ballerina/tests/SmtpEmailSendWithOptions.bal, ballerina/tests/SmtpSimpleSecureEmailSend.bal, ballerina/tests/SmtpSimpleSecureEmailSendWithOptions.bal
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/2443
=> Update usage of check statement

examples/gmail-smtp-client/README.md
=> Reduce README image size

examples/gmail-smtp-client/README.md
=> Move example image into a dev

docs/spec/spec.md
Resolves https://github.com/ballerina-platform/ballerina-standard-library/issues/2194
=> Add the specification document

README.md, ballerina/Module.md, ballerina/Package.md
> $subject 
Related to [#2657](https://github.com/ballerina-platform/ballerina-standard-library/issues/2657)
N/A
=> Update the content of Package.md and README.md file

load-tests/smtp_client/src/service.bal
=> Fix build failure in email load-test

load-tests/smtp_client/results/summary.csv, load-tests/smtp_client/src/service.bal
=> Fix logic issue in load-test

load-tests/smtp_client/scripts/load_test/main.bal
=> Update load-test duration

load-tests/smtp_client/scripts/load_test/main.bal, load-tests/smtp_client/src/service.bal
=> Add logs for load-tests

load-tests/smtp_client/src/service.bal
=> Update sleeping-interval for load-test back-end

ballerina/Ballerina.toml, build-config/resources/Ballerina.toml
=> Update distribution version to `2201.0.4`

docs/spec/spec.md
=> Reformat Email spec

native/build.gradle
> $subject
Related to [#2802](https://github.com/ballerina-platform/ballerina-standard-library/issues/2802)
N/A
=> Remove ballerina-core dependency

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties, native/src/main/java/io/ballerina/stdlib/email/server/EmailListener.java
$subject
https://github.com/ballerina-platform/ballerina-standard-library/issues/3517
=> Fix failing build for type reference support

gradle.properties
=> [2201.3.x] Update mime version

ballerina/imap_client_endpoint.bal, ballerina/imap_listener_endpoint.bal, ballerina/pop_client_endpoint.bal, ballerina/pop_listener_endpoint.bal
> $subject
Fixes [#3898](https://github.com/ballerina-platform/ballerina-standard-library/issues/3898)
N/A
=> [2201.3.x] Update default configurations in email clients and listeners

gradle.properties
=> Update ballerina/task dependency version

ballerina/Dependencies.toml, gradle.properties
=> Update std lib versions

README.md
Update the Ballerina library word.
=> Update the `Ballerina library` word

ballerina/Ballerina.toml, ballerina/CompilerPlugin.toml, ballerina/Dependencies.toml, build-config/resources/Ballerina.toml, gradle.properties
=> Update dependency versions for U10

native/src/main/java/io/ballerina/stdlib/email/client/SmtpClient.java
=> Improve send failed exception with invalid addresses

native/src/main/java/io/ballerina/stdlib/email/client/SmtpClient.java
=> [Master] Improve send failed exception with invalid addresses

ballerina/Dependencies.toml, native/src/main/java/io/ballerina/stdlib/email/server/EmailListener.java, native/src/main/java/io/ballerina/stdlib/email/util/EmailConstants.java
=> Replace worker runtime API
